/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and receive session cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Signed in. Sets `TMS_SESSION` cookie. */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                /** @description INVALID_CREDENTIALS (generic message) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out (clears session cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active users (assignee picker) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSummary"][];
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search/filter tickets (paginated, newest-updated first) */
        get: {
            parameters: {
                query?: {
                    /** @description Case-insensitive keyword over key, title, description (literal match) */
                    q?: string;
                    status?: components["schemas"]["TicketStatus"];
                    /**
                     * @description `mine` = reported by current user (default), `all` = every ticket,
                     *     `assigned` = assigned to current user with status OPEN or IN_PROGRESS, ordered by
                     *     priority (CRITICAL first), then oldest created, then reference. `q` and `status`
                     *     combine with AND, so `view=assigned&status=RESOLVED|CLOSED` returns no items.
                     */
                    view?: "mine" | "all" | "assigned";
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketPage"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        /** Create ticket (status OPEN, reporter = current user) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTicketRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description /api/v1/tickets/{ticketKey} */
                        Location?: string;
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketDetail"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counters for the signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketSummaryCounts"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketKey}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketKey: components["parameters"]["TicketKey"];
            };
            cookie?: never;
        };
        /** Ticket details with comments and history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketKey: components["parameters"]["TicketKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketDetail"];
                    };
                };
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update title, description, priority and/or assignee (not status)
         * @description Only supplied fields are changed. Unknown properties (including `status`) are rejected
         *     with 400. Rejected with 409 TICKET_CLOSED when the ticket is CLOSED.
         */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description ETag from the last read of the ticket */
                    "If-Match": components["parameters"]["IfMatch"];
                };
                path: {
                    ticketKey: components["parameters"]["TicketKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTicketRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketDetail"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                412: components["responses"]["VersionConflict"];
                428: components["responses"]["PreconditionRequired"];
            };
        };
        trace?: never;
    };
    "/tickets/{ticketKey}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketKey: components["parameters"]["TicketKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change status (only OPEN→IN_PROGRESS→RESOLVED→CLOSED) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description ETag from the last read of the ticket */
                    "If-Match": components["parameters"]["IfMatch"];
                };
                path: {
                    ticketKey: components["parameters"]["TicketKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransitionRequest"];
                };
            };
            responses: {
                /** @description Transition applied */
                200: {
                    headers: {
                        ETag: components["headers"]["ETag"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketDetail"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
                /** @description INVALID_STATUS_TRANSITION (ticket unchanged) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "type": "about:blank",
                         *       "title": "Status change not allowed",
                         *       "status": 409,
                         *       "detail": "A ticket in OPEN can only move to IN_PROGRESS.",
                         *       "code": "INVALID_STATUS_TRANSITION",
                         *       "currentStatus": "OPEN",
                         *       "allowedNextStatus": "IN_PROGRESS",
                         *       "traceId": "4bf92f3577b34da6"
                         *     }
                         */
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                412: components["responses"]["VersionConflict"];
                428: components["responses"]["PreconditionRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketKey}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketKey: components["parameters"]["TicketKey"];
            };
            cookie?: never;
        };
        /** Comments, oldest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketKey: components["parameters"]["TicketKey"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Add comment (author = current user); 409 TICKET_CLOSED if closed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ticketKey: components["parameters"]["TicketKey"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TicketStatus: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
        /** @enum {string} */
        Priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        CurrentUser: {
            /** Format: int64 */
            id: number;
            username: string;
            displayName: string;
            email: string;
        };
        UserSummary: {
            /** Format: int64 */
            id: number;
            displayName: string;
            email?: string;
        };
        CreateTicketRequest: {
            title: string;
            description: string;
            priority: components["schemas"]["Priority"];
            /** Format: int64 */
            assigneeId: number;
        };
        UpdateTicketRequest: {
            title?: string;
            description?: string;
            priority?: components["schemas"]["Priority"];
            /** Format: int64 */
            assigneeId?: number;
        };
        TransitionRequest: {
            targetStatus: components["schemas"]["TicketStatus"];
        };
        CreateCommentRequest: {
            body: string;
        };
        TicketSummary: {
            /** @example TMS-42 */
            key: string;
            title: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["Priority"];
            assignee: components["schemas"]["UserSummary"];
            reporter: components["schemas"]["UserSummary"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TicketPage: {
            items: components["schemas"]["TicketSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalItems: number;
            totalPages: number;
        };
        TicketSummaryCounts: {
            /**
             * Format: int64
             * @description Tickets assigned to the signed-in user in status OPEN or IN_PROGRESS; equals `totalItems` of `GET /tickets?view=assigned` without q/status.
             */
            assignedPending: number;
        };
        TicketDetail: components["schemas"]["TicketSummary"] & {
            description: string;
            /** Format: date-time */
            resolvedAt?: string | null;
            /** Format: date-time */
            closedAt?: string | null;
            /** Format: int64 */
            version: number;
            /** @description The only status this ticket may move to; null when CLOSED */
            allowedNextStatus: components["schemas"]["TicketStatus"] | null;
            comments: components["schemas"]["Comment"][];
            history: components["schemas"]["HistoryEntry"][];
        };
        Comment: {
            /** Format: int64 */
            id: number;
            author: components["schemas"]["UserSummary"];
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        HistoryEntry: {
            /** Format: int64 */
            id: number;
            actor: components["schemas"]["UserSummary"];
            /** @enum {string} */
            changeType: "CREATED" | "FIELD_UPDATED" | "STATUS_CHANGED";
            field?: string | null;
            oldValue?: string | null;
            newValue?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        FieldError: {
            field: string;
            message: string;
        };
        /** @description RFC 9457 Problem Details with project extensions */
        Problem: {
            /** @default about:blank */
            type: string;
            /** @description Short user-friendly heading for the modal */
            title: string;
            status: number;
            /** @description User-friendly explanation */
            detail?: string;
            instance?: string;
            /** @enum {string} */
            code: "VALIDATION_FAILED" | "INVALID_CREDENTIALS" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "TICKET_NOT_FOUND" | "INVALID_STATUS_TRANSITION" | "TICKET_CLOSED" | "VERSION_CONFLICT" | "PRECONDITION_REQUIRED" | "INTERNAL_ERROR";
            errors?: components["schemas"]["FieldError"][];
            currentStatus?: components["schemas"]["TicketStatus"];
            allowedNextStatus?: components["schemas"]["TicketStatus"] | null;
            traceId?: string;
        };
    };
    responses: {
        /** @description VALIDATION_FAILED with per-field errors */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Please correct the highlighted fields",
                 *       "status": 400,
                 *       "detail": "2 fields need attention.",
                 *       "code": "VALIDATION_FAILED",
                 *       "errors": [
                 *         {
                 *           "field": "title",
                 *           "message": "Title must be between 3 and 150 characters."
                 *         },
                 *         {
                 *           "field": "assigneeId",
                 *           "message": "Please choose an assignee."
                 *         }
                 *       ],
                 *       "traceId": "4bf92f3577b34da6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description UNAUTHENTICATED (missing/expired session) */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description TICKET_NOT_FOUND */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description TICKET_CLOSED (closed tickets are read-only) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description VERSION_CONFLICT (ticket changed since last read; reload) */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description PRECONDITION_REQUIRED (If-Match header missing) */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        TicketKey: string;
        /** @description ETag from the last read of the ticket */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Quoted ticket version, e.g. `"3"` */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
